# Generated by Django 3.2.5 on 2021-07-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generated_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.schema')),
            ],
        ),
    ]
