# Generated by Django 3.2.5 on 2021-07-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_generated_csv_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_csv',
            name='path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
